// <auto-generated />
using DotNetSigningServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace dotnetsigningserver.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DotNetSigningServer.Models.SigningData", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CertificatePem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasDefaultValue("Signature1");

                    b.Property<string>("HashToSign")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PresignedPdfPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TsaPassword")
                        .HasColumnType("text");

                    b.Property<string>("TsaUrl")
                        .HasColumnType("text");

                    b.Property<string>("TsaUsername")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SigningData");
                });
#pragma warning restore 612, 618
        }
    }
}
